version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
      args:
        UID: 1000

    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    network_mode: host

    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./sql_data:/var/lib/postgresql/scripts

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always

    network_mode: host

  web:
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    restart: always
    tty: true

    network_mode: host

    volumes:
      - ./public:/usr/src/app/public

volumes:
  pgdata: