FROM postgres:16

# setting up environment
RUN apt-get update

RUN apt-get install -y git
RUN apt-get install -y build-essential
RUN apt-get install -y bison
RUN apt-get install -y flex
RUN apt-get install -y libreadline-dev
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y gosu


# building postgres
RUN mkdir /repo
WORKDIR /repo
RUN git clone https://github.com/postgres/postgres.git -b REL_16_STABLE
WORKDIR /repo/postgres
RUN ./configure --without-icu
RUN make
RUN rm /repo/postgres/src/tutorial/complex.c
COPY ./sql_data/complex.cpp /repo/postgres/src/tutorial
WORKDIR /repo/postgres/src/tutorial
RUN make NO_PGXS=1
RUN chown postgres:postgres complex.so


# entrypoint script
COPY ./start.sh /docker-entrypoint-initdb.d/start.sh
RUN chmod +x /docker-entrypoint-initdb.d/start.sh


# setting up user
ARG UID
RUN groupmod -g $UID postgres
RUN usermod -u $UID -g $UID postgres
USER postgres
WORKDIR /var/lib/postgresql